In [177]:
import pandas as pd
import script_reglas
import re 
import unicodedata
import nltk
from nltk.stem.snowball import SnowballStemmer
from numpy import reshape
from numpy import shape
from numpy import concatenate
from numpy import nan
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from xgboost import XGBClassifier

from sklearn.externals import joblib

In [145]:
respuestas=pd.read_excel('s3://presidencia-mi-salud/processed/results_export_964.xlsx', encoding='utf-8')

respuestas=respuestas[['Contact UUID', 'URN', 'Name', 'Groups', 'Response 9 (Text) - uncaught']]
respuestas.columns=['id_contacto', 'urn', 'nombre_contacto', 'listas', 'texto']


categoria_reglas=pd.DataFrame()
for i in range(0, respuestas.shape[0]):
    respuesta_regla=pd.DataFrame(script_reglas.procesa_reglas(str(respuestas['texto'].iloc[i])), index=[i])
    categoria_reglas=pd.concat([categoria_reglas, respuesta_regla])
respuestas=pd.concat([respuestas[['id_contacto', 'urn', 'nombre_contacto', 'listas']],
                      categoria_reglas], axis=1)
print(respuestas.shape)
respuestas=respuestas.loc[respuestas.texto!='nan']
print(respuestas.shape)
etiquetado=pd.read_csv('s3://presidencia-mi-salud/processed/clasificacion_misalud.csv')

respuestas_etiquetas=pd.merge(respuestas, etiquetado[['id_contacto', 'categ_opi', 'Clasificacion final']],how='left',
                              on=['id_contacto'])
respuestas_etiquetas.columns=['id_contacto', 'urn', 'nombre_contacto', 'listas', 'cc', 'result',
       'texto', 'texto_proc', 'wc', 'categ_opi', 'categ_final']

respuestas_etiquetas=respuestas_etiquetas.loc[respuestas_etiquetas.result=='modelo']

respuestas_etiquetas.categ_final.loc[respuestas_etiquetas.categ_final.isnull()]=respuestas_etiquetas.categ_opi.loc[respuestas_etiquetas.categ_final.isnull()]


respuestas_etiquetas.categ_final.loc[(respuestas_etiquetas.categ_final=='cancelar')]='respuesta'
respuestas_etiquetas.categ_final.loc[(respuestas_etiquetas.categ_final=='otra_registro')]='otra'
respuestas_etiquetas.categ_final.loc[(respuestas_etiquetas.texto=='¿Cómo saben que estoy triste?')]='otra'


map_fac=pd.factorize(respuestas_etiquetas.categ_final)[1]
respuestas_etiquetas.categ_final=pd.factorize(respuestas_etiquetas.categ_final)[0]
respuestas_etiquetas.categ_opi=respuestas_etiquetas.categ_final

label_map={0:'otra',
          1:'informacion',
          2: 'nacimiento',
          3: 'respuesta',
          4: 'emergencia',
          5: 'pregunta',
          6: 'pregunta_busca trabajo',
          7: 'otra_queja',
          8: 'pregunta_medica'}

respuestas_etiquetas.categ_opi=respuestas_etiquetas.categ_final.map(label_map)

(3045, 9)
(2472, 9)


/Users/pepe_opi/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [153]:
flujos=pd.read_csv('s3://presidencia-mi-salud/processed/flujos_peticiones.csv')

flujos=flujos[['contact_uuid', 'flujo_penultimo', 'flujo_ultimo', 'ultimo_tmstmp','penultimo_tmstmp' ]]

flujos.ultimo_tmstmp=flujos.ultimo_tmstmp.str.replace('Z|T', ' ')
flujos.penultimo_tmstmp=flujos.penultimo_tmstmp.str.replace('Z|T', ' ')

flujos.penultimo_tmstmp=flujos.penultimo_tmstmp.str.strip()
flujos.ultimo_tmstmp=flujos.ultimo_tmstmp.str.strip()
from datetime import datetime
for i in range(0, flujos.shape[0]):
    if  (flujos.ultimo_tmstmp[i] is nan) == False:
        flujos.ultimo_tmstmp[i]=datetime.strptime(flujos.ultimo_tmstmp[i],
                  "%Y-%m-%d %H:%M:%S.%f")
    else: 
        flujos.ultimo_tmstmp[i]=None
    if  (flujos.penultimo_tmstmp[i] is nan) == False:
        flujos.penultimo_tmstmp[i]=datetime.strptime(flujos.penultimo_tmstmp[i],
                  "%Y-%m-%d %H:%M:%S.%f")
    else: 
        flujos.penultimo_tmstmp[i]=None
        
horas_ultimos=pd.DataFrame()
for i in range(0, flujos.shape[0]):
    hora_ultimo=int(flujos.ultimo_tmstmp[i].strftime('%H'))
    hora_ultimo=pd.DataFrame({'hora_ultimo':hora_ultimo}, index=[i])
    horas_ultimos=pd.concat([horas_ultimos, hora_ultimo])
flujos=pd.concat([flujos, horas_ultimos], axis=1)   

flujos.columns=['id_contacto', 'flujo_penultimo', 'flujo_ultimo', 'ultimo_tmstmp', 'penultimo_tmstmp', 'hora_ultimo']

In [155]:
respuestas_etiquetas=pd.merge(flujos[['id_contacto', 'hora_ultimo']], respuestas_etiquetas, how='inner',on='id_contacto' )

In [326]:
train_target=respuestas_etiquetas['categ_opi'].values

In [327]:
train_texto=respuestas_etiquetas['texto'].values

In [328]:
def procesa_texto(texto):
    texto=texto.lower()
    texto=re.sub('^[ \t]+|[ \t]+$', '', texto) 

    texto=re.sub('[^\w\s]','', texto)

    #texto=re.sub('^[ \t]+|[ \t]+$', '', texto)

    texto=script_reglas.give_emoji_free_text(texto)

    texto=unicodedata.normalize('NFD', texto).encode('ascii', 'ignore').decode('utf-8')
    wc=len(str(texto).split(" "))
    texto=re.sub('ola|\n|buena noche|buenos dias|buenos dia|buen dia|buenas noches|buenas tardes|buenas tarde|buen dia|bien dia|buena tardes|buena tarde|saludos|hola','', texto)
    texto=re.sub('^[ \t]+|[ \t]+$', '', texto)
    return texto , wc

stemmer = SnowballStemmer("spanish")


def tokenize_and_stem(text):
    # first tokenize by sentence, then by word to ensure that punctuation is caught as it's own token
    tokens = [word for sent in nltk.sent_tokenize(text) for word in nltk.word_tokenize(sent)]
    filtered_tokens = []
    # filter out any tokens not containing letters (e.g., numeric tokens, raw punctuation)
    for token in tokens:
        if re.search('[a-zA-Z]', token):
            filtered_tokens.append(token)
    stems = [stemmer.stem(t) for t in filtered_tokens]
    return stems

In [341]:
#train_texto_stem.append(procesa_texto(train_texto[0])[0])
train_texto_stem=[]

In [347]:
train_texto_stem.append(procesa_texto(train_texto[i])[0])

In [370]:
wc=[]

for i in range(0, shape(train_texto)[0]):
    train_texto[i], wc.append(procesa_texto(train_texto[i])[1])
    #train_texto_stem.append(tokenize_and_stem(train_texto[i]))
    #train_texto_stem[i]=' '.join(train_texto_stem[i])
wc=reshape(wc, (-1, 1))

hora=respuestas_etiquetas.hora_ultimo.values
hora=reshape(hora, (-1, 1))

In [371]:
stop=nltk.corpus.stopwords.words("spanish")

for i in range(0, shape(stop)[0]):
    stop[i]=unicodedata.normalize('NFD', stop[i]).encode('ascii', 'ignore').decode('utf-8')

In [374]:
tfidf = TfidfVectorizer(sublinear_tf=True,
                        min_df=0.006, norm='l2', encoding='utf-8', ngram_range=([1, 1]),
                        stop_words=stop)

features_stem_tfidf = tfidf.fit(train_texto)
features_stem = features_stem_tfidf.transform(train_texto)

labels = respuestas_etiquetas.categ_final
features_stem.shape

(974, 389)

In [375]:
features_stem=features_stem.toarray()
pca=TruncatedSVD(n_components=33)
pca=pca.fit(features_stem, features_stem)
features_stem_pca=pca.transform(features_stem)

In [376]:
x_train=concatenate((features_stem_pca, wc), axis=1)

In [377]:
x_train=concatenate((x_train, hora), axis=1)

In [378]:
clasificador=XGBClassifier(metrics='auc')
clasificador=clasificador.fit(X=x_train,y=train_target)


In [379]:
joblib.dump(features_stem_tfidf, './modelo/mat_tfidf.pkl') #1
joblib.dump(pca, './modelo/pca.pkl')  #2
joblib.dump(clasificador, './modelo/modelo.pkl') # 3
 

['./modelo/modelo.pkl']

In [464]:
counts

array([ 0.00616016,  0.04928131,  0.00718686,  0.28644764,  0.14887064,
        0.34599589,  0.05954825,  0.01848049,  0.07802875])

In [461]:



contact_uuid='7159a4a1-0778-487e-b189-dbc126018dd5'
response = requests.get("http://10.20.55.67/api/v2/runs.json",
                            headers={"Authorization": "Token 0032fe79dbddceae3f4a86e86a726e16b88ec88e"},
                            params={"contact": contact_uuid})

response=json.loads(response.text)
hora=response['results'][0]['created_on']
hora=int(hora[11:13])


texto='Hola, buenas tardes, dónde puedo conseguir la vacuna antihepatitis B?'

texto, wc =procesa_texto(texto)

wc=reshape(wc, (-1, 1))
hora=reshape(hora, (-1, 1))


tfidf=features_stem_tfidf.transform([texto])
features=pca.transform(tfidf)

features=concatenate((features, wc), axis=1)
features=concatenate((features, hora), axis=1)

labs, counts = unique(train_target, return_counts=True)
counts=counts/counts.sum()

proba=clasificador.predict_proba(features)

minimo_conc=80343.143718211984

conc=proba*100
conc=conc*conc
conc=conc.sum()

if conc<minimo_conc:
    manda_etiquetas

proba_orig=proba
proba=proba/counts






In [472]:
check=pd.read_csv('./datos/pred_ponde_71.csv')





In [473]:
conc_base=check[['4', '1', '2', '0', '7', '5', '6', '8', '3']].loc[0].values*100

#conc_base=check[['4', '1', '2', '0', '7', '5', '6', '8', '3']]

conc_base=conc_base*conc_base

conc_base=conc_base.sum(axis=0)


In [474]:
check


Unnamed: 0                                              texto         0  \
0            94  Hola, oye, dónde puedo reimprimir mipóliza del...  0.036351   
1           268  Buen día podrían indicarme donde puedo encontr...  0.033792   
2           666  Hola, buenas tardes, dónde puedo conseguir la ...  0.070017   
3           200  Hola quiero reportar un drenaje que esta salie...  0.067149   
4           754  Buenas noches quisiera saber como puedo conseg...  0.044440   
5           347  Buenos días \nQuisiera saber en donde puedo co...  0.041031   
6           169  Quisiera saber si me pueden dar información so...  0.047297   
7           360  Buenos dias quisiera sabe cuando tendran las v...  0.054579   
8           418  Hola \nMe gustaria saber si ya hay vacunas de ...  0.098366   
9           164  Hola buenos dias. El seguro popular atiende ta...  0.107620   
10          609            Hola donde consigo la de la hepatitis A  0.073878   
11            8                         Mi bebé esta deshidratado   0.083919   
12          947  Hola me gustaría saber, si aún está vigente mi...  0.121436   
13          694  Hola, buenos días! quería saber que tengo que ...  0.064310   
14          807  buen dia, me puden ayudar a confirmar si este ...  3.281664   
15          163  buenos dias disculpe la molestia pero si la se...  0.099333   
16          410  Buenos dias disculpe donde puedo reportar un e...  0.099454   
17          912          Hay bolsa de trabajo abierta en cd.juarez  0.100716   
18          138  Que tal buena tardes \nCuando habrá vacunas pa...  0.119590   
19          835  Buenas tardes.. Me podrían informar si hay cam...  0.155538   
20          673  ¿Saben si ya han distribuido vacunas contra he...  0.091816   
21          889  Hola ¿Dónde puedo obtener la aplicación de la ...  0.129763   
22          300  @SSalud_mx dónde puedo encontrar la vacuna par...  0.083081   
23          819  Disculpe donde pueden aplicarme el refuerzo de...  0.112907   
24          624  Buenas noches, está abierta la bolsa de trabaj...  0.084684   
25          957  Buenas noches .. Disculpe ustedes saben en don...  0.039295   
26          671  Buen día, quisiera saber cuando llegara la vac...  0.065446   
27          833  Secretaria de Salud informa: que NO se debe co...  3.253922   
28          423  Buenos días.\n\n¿Dónde puedo conseguir la vacu...  0.118401   
29          934  Hola buenas tardes ya hay vacuna del hepatitis...  0.155059   
..          ...                                                ...       ...   
545         155  Buen dia, quisiera preguntar si me pueden apoy...  1.025173   
546         239  Hola buenos días oye donde puedo denunciar mal...  0.259351   
547         757  Aka..en mi rancho el sentro de salud no tienes...  0.309183   
548         827  Buen día, anda circulando en la aplicación Wha...  2.122220   
549         923  Hola buen di, me gustaría saber algo sobre el ...  1.817885   
550         255  Hola quiero saber si tiene algún costo el dona...  0.319171   
551         946  @Tu_IMSS ayer le pusieron la diálisis a mi her...  0.664891   
552         710  I am working for an advertising and marketing ...  2.081573   
553         400                                       soi el papa´  1.837801   
554         555  Buenos dias por que se esta obligando alas per...  1.990879   
555          58  Buenas noches,\nDisculpen tendrán algún calend...  0.393000   
556         542  Hoy fui a consulta y pese a que el doctor me d...  1.002149   
557         326  Hola buenas  noches ...   ante que  nada un sa...  0.986585   
558         102  Es bueno tener relaciones sexuales durante el ...  2.041909   
559         883  Buenos días una pregunta soy profesional técni...  1.198897   
560          24                                     Ya tive ami bb  1.876928   
561          12                  ¿Por que mi bebe estornuda mucho?  2.039934   
562         437  ¾¯„ù´Œ‚˜A87ecF_e5hKJL6JTy‰\n€MOVISTAR–êMa...  1.273546   
563  

In [384]:
print(check.texto[2])
print(check[['4', '1', '2', '0', '7', '5', '6', '8', '3']].loc[2].values)
check[['4', '1', '2', '0', '7', '5', '6', '8', '3']].loc[2].values.argmax()

Hola, buenas tardes, dónde puedo conseguir la vacuna antihepatitis B?
[ 0.04740137  0.09008432  0.04060991  0.0700173   0.04708537  2.78425212
  0.05396583  0.02314679  0.01191382]


5

In [397]:
from numpy import array

In [399]:
aux=[0.070017, 0.090084, 0.040610, 0.011914, 0.047401, 2.784252, 0.053966, 0.047085, 0.023147]
aux=array(aux)
aux=aux*100
aux=aux.power(2)

aux.sum()

AttributeError: 'numpy.ndarray' object has no attribute 'power'

In [385]:
print(proba)
proba.argmax()

[[ 0.13479312  0.17276355  0.04560488  0.1115102   0.16420978  2.63539707
   0.29918952  0.07193476  0.03790728]]


5

In [463]:
(check[['4', '1', '2', '0', '7', '5', '6', '8', '3']].loc[2].values)-proba

array([[-0.08739175, -0.08267924, -0.00499497, -0.04149291, -0.11712441,
         0.14885505, -0.24522369, -0.04878797, -0.02599346]])

In [438]:
respuestas_etiquetas['id_contacto'].loc[respuestas_etiquetas.texto=='Hola, buenas tardes, dónde puedo conseguir la vacuna antihepatitis B?'].values


array(['7159a4a1-0778-487e-b189-dbc126018dd5'], dtype=object)

In [316]:
respuestas_etiquetas.loc[respuestas_etiquetas.texto=='Hola, buenas tardes, dónde puedo conseguir la vacuna antihepatitis B?']


666    21
Name: hora_ultimo, dtype: int64

In [261]:

print(asarray((labs, counts)).T)

[['emergencia' 0.006160164271047228]
 ['informacion' 0.049281314168377825]
 ['nacimiento' 0.007186858316221766]
 ['otra' 0.2864476386036961]
 ['otra_queja' 0.14887063655030802]
 ['pregunta' 0.3459958932238193]
 ['pregunta_busca trabajo' 0.059548254620123205]
 ['pregunta_medica' 0.018480492813141684]
 ['respuesta' 0.07802874743326489]]


In [262]:
counts

array([ 0.00616016,  0.04928131,  0.00718686,  0.28644764,  0.14887064,
        0.34599589,  0.05954825,  0.01848049,  0.07802875])